"""add_paper_checking

Revision ID: 3d322eebe3ca
Revises: a5ef8569e97a
Create Date: 2026-01-26 09:19:34.725005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d322eebe3ca'
down_revision: Union[str, Sequence[str], None] = 'a5ef8569e97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('question_paper_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Map of question_id to grading criteria'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_paper_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_paper_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'UPLOADED', 'OCR_PROCESSING', 'GRADING', 'COMPLETED', 'FAILED', name='submission_status'), nullable=False),
    sa.Column('input_file_url', sa.String(length=500), nullable=False, comment='URL of the uploaded answer sheet (PDF/Image)'),
    sa.Column('student_name', sa.String(length=255), nullable=True, comment='Extracted or provided student name'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='Raw text content from OCR'),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True, comment='Overall performace summary'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graded_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True, comment='Snapshot of question text'),
    sa.Column('student_answer_text', sa.Text(), nullable=False, comment='Part of OCR text identified as this answer'),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True, comment='Specific feedback for this answer'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='AI confidence in grading (0-1)'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graded_answers')
    op.drop_table('submissions')
    op.drop_table('answer_keys')
    # ### end Alembic commands ###
