"""initial_core_tables

Revision ID: 5c4957ae1653
Revises: 
Create Date: 2026-01-25 21:40:44.125642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c4957ae1653'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable uuid-ossp extension for uuid_generate_v4()
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Institution name in English'),
    sa.Column('name_gujarati', sa.String(length=255), nullable=True, comment='Institution name in Gujarati'),
    sa.Column('type', sa.Enum('SCHOOL', 'COLLEGE', 'COACHING', 'SELF', name='institution_type'), nullable=False, comment='school, college, coaching, self'),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='MinIO logo URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='subscription_plan'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_institutions_active', 'institutions', ['is_active'], unique=False)
    op.create_index('idx_institutions_city', 'institutions', ['city'], unique=False)
    op.create_index('idx_institutions_type', 'institutions', ['type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Role identifier (e.g., teacher, student)'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='Display name in English'),
    sa.Column('display_name_gujarati', sa.String(length=100), nullable=True, comment='Display name in Gujarati'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='JSON object with permission flags'),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='True for built-in roles'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True, comment='Associated institution'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment="User's role"),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Login email'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Full name in English'),
    sa.Column('full_name_gujarati', sa.String(length=255), nullable=True, comment='Full name in Gujarati'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True, comment='Profile picture URL (MinIO)'),
    sa.Column('language_preference', sa.Enum('GUJARATI', 'ENGLISH', 'BILINGUAL', name='language_preference'), nullable=False, comment='gu, en, or gu-en'),
    sa.Column('grade_level', sa.String(length=20), nullable=True, comment="Student's grade (1-12, UG)"),
    sa.Column('subjects', postgresql.ARRAY(sa.String()), nullable=True, comment="Teacher's subjects array"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_institution', 'users', ['institution_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Session owner'),
    sa.Column('refresh_token', sa.String(length=500), nullable=False, comment='JWT refresh token'),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Device/browser info'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP (IPv4/IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser user agent'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration time'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_sessions_active', 'user_sessions', ['is_active'], unique=False)
    op.create_index('idx_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_user', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires', table_name='user_sessions')
    op.drop_index('idx_user_sessions_active', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_institution', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('idx_institutions_type', table_name='institutions')
    op.drop_index('idx_institutions_city', table_name='institutions')
    op.drop_index('idx_institutions_active', table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
