"""add_paper_checking

Revision ID: 6b5032d176f6
Revises: 3d322eebe3ca
Create Date: 2026-01-26 09:21:36.334338

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6b5032d176f6'
down_revision: Union[str, Sequence[str], None] = '3d322eebe3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
