"""add_learning_module

Revision ID: 89ada99de96b
Revises: 6b5032d176f6
Create Date: 2026-01-26 10:58:36.788340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89ada99de96b'
down_revision: Union[str, Sequence[str], None] = '6b5032d176f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topics',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='Markdown or HTML content'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='learning_difficulty_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('gujarati_word', sa.String(length=255), nullable=False),
    sa.Column('english_translation', sa.String(length=255), nullable=False),
    sa.Column('transliteration', sa.String(length=255), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_sentence_english', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_items_category'), 'vocabulary_items', ['category'], unique=False)
    op.create_index(op.f('ix_vocabulary_items_gujarati_word'), 'vocabulary_items', ['gujarati_word'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('exercise_type', sa.Enum('FLASHCARD', 'WORD_MATCH', 'SENTENCE_BUILDER', 'QUIZ', 'PICTURE_WORD', 'VERB_CONJUGATION', name='exercise_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('grammar_topic_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.String(length=50), nullable=False),
    sa.Column('vocabulary_mastered', sa.Integer(), nullable=False),
    sa.Column('grammar_concepts_completed', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_word_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_item_id', sa.UUID(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_word_progress_user_review', 'user_word_progress', ['user_id', 'next_review_date'], unique=False)
    op.create_index(op.f('ix_user_word_progress_next_review_date'), 'user_word_progress', ['next_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_word_progress_next_review_date'), table_name='user_word_progress')
    op.drop_index('idx_word_progress_user_review', table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_table('learning_profiles')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_vocabulary_items_gujarati_word'), table_name='vocabulary_items')
    op.drop_index(op.f('ix_vocabulary_items_category'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_table('grammar_topics')
    # ### end Alembic commands ###
