"""add_teaching_tools

Revision ID: a5ef8569e97a
Revises: 82d16b29c982
Create Date: 2026-01-26 09:03:51.816861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5ef8569e97a'
down_revision: Union[str, Sequence[str], None] = '82d16b29c982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_tools',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Creator ID'),
    sa.Column('tool_type', sa.Enum('MIND_MAP', 'LESSON_PLAN', 'ANALOGY', name='tool_type'), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tool specific content structure'),
    sa.Column('language', sa.String(length=10), nullable=False, comment='gu, en, gu-en'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Allow sharing'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tools_created', 'teaching_tools', ['created_at'], unique=False)
    op.create_index('idx_tools_type', 'teaching_tools', ['tool_type'], unique=False)
    op.create_index('idx_tools_user', 'teaching_tools', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tools_user', table_name='teaching_tools')
    op.drop_index('idx_tools_type', table_name='teaching_tools')
    op.drop_index('idx_tools_created', table_name='teaching_tools')
    op.drop_table('teaching_tools')
    # ### end Alembic commands ###
