"""add_documents_and_question_papers

Revision ID: c3b9aec2ff24
Revises: 5c4957ae1653
Create Date: 2026-01-26 08:09:34.679112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3b9aec2ff24'
down_revision: Union[str, Sequence[str], None] = '5c4957ae1653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Document owner'),
    sa.Column('institution_id', sa.UUID(), nullable=True, comment='Associated institution'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='MinIO storage URL'),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'TXT', 'IMAGE', name='file_type'), nullable=False, comment='pdf, docx, txt'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True, comment='Extracted text content'),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Additional document metadata'),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status'), nullable=False, comment='Processing status'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Number of pages'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='Detected language (gu, en, gu-en)'),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='Subject category'),
    sa.Column('grade_level', sa.String(length=20), nullable=True, comment='Grade level'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_active', 'documents', ['is_active'], unique=False)
    op.create_index('idx_documents_created', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['processing_status'], unique=False)
    op.create_index('idx_documents_user', 'documents', ['user_id'], unique=False)
    op.create_table('question_papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Paper creator'),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True, comment='Source document (if RAG generated)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Paper title'),
    sa.Column('title_gujarati', sa.String(length=255), nullable=True, comment='Title in Gujarati'),
    sa.Column('subject', sa.String(length=100), nullable=False, comment='Subject name'),
    sa.Column('grade_level', sa.String(length=20), nullable=True, comment='Target grade (e.g., 10, 12, UG)'),
    sa.Column('total_marks', sa.Integer(), nullable=False, comment='Maximum marks'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Exam duration in minutes'),
    sa.Column('language', sa.String(length=10), nullable=False, comment='Paper language (gu, en, gu-en)'),
    sa.Column('difficulty_distribution', postgresql.JSONB(astext_type=sa.Text()), server_default='{"easy": 30, "medium": 50, "hard": 20}', nullable=False, comment='% distribution by difficulty'),
    sa.Column('question_type_distribution', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Count by question type'),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Exam instructions'),
    sa.Column('instructions_gujarati', sa.Text(), nullable=True, comment='Instructions in Gujarati'),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'PUBLISHED', name='paper_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_papers_created', 'question_papers', ['created_at'], unique=False)
    op.create_index('idx_question_papers_status', 'question_papers', ['status'], unique=False)
    op.create_index('idx_question_papers_subject', 'question_papers', ['subject'], unique=False)
    op.create_index('idx_question_papers_user', 'question_papers', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False, comment='Order in paper'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='Question content'),
    sa.Column('question_text_gujarati', sa.Text(), nullable=True, comment='Gujarati version'),
    sa.Column('question_type', sa.Enum('MCQ', 'SHORT_ANSWER', 'LONG_ANSWER', 'TRUE_FALSE', 'FILL_BLANK', name='question_type'), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False, comment='Question marks'),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_level'), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True, comment='Expected answer'),
    sa.Column('answer_gujarati', sa.Text(), nullable=True, comment='Answer in Gujarati'),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=True, comment='MCQ options'),
    sa.Column('correct_option', sa.Integer(), nullable=True, comment='Correct MCQ option index (0-based)'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='Answer explanation'),
    sa.Column('bloom_level', sa.String(length=50), nullable=True, comment="Bloom's taxonomy level"),
    sa.Column('topic', sa.String(length=200), nullable=True, comment='Related topic/chapter'),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True, comment='Answer keywords for matching'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('idx_questions_paper', 'questions', ['paper_id'], unique=False)
    op.create_index('idx_questions_type', 'questions', ['question_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_questions_type', table_name='questions')
    op.drop_index('idx_questions_paper', table_name='questions')
    op.drop_index('idx_questions_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_question_papers_user', table_name='question_papers')
    op.drop_index('idx_question_papers_subject', table_name='question_papers')
    op.drop_index('idx_question_papers_status', table_name='question_papers')
    op.drop_index('idx_question_papers_created', table_name='question_papers')
    op.drop_table('question_papers')
    op.drop_index('idx_documents_user', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_created', table_name='documents')
    op.drop_index('idx_documents_active', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
