"""add_checked_papers_table

Revision ID: d8b378484d56
Revises: ca9e4bfd7d86
Create Date: 2026-01-27 22:13:36.794054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b378484d56'
down_revision: Union[str, Sequence[str], None] = 'ca9e4bfd7d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, delete existing answer_keys data since the schema changed significantly
    # The old format (content JSONB) is incompatible with the new format (answers JSONB array)
    op.execute("DELETE FROM answer_keys")
    
    op.create_table('checked_papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('answer_key_id', sa.UUID(), nullable=False, comment='Answer key used for grading'),
    sa.Column('teacher_id', sa.UUID(), nullable=False, comment='Teacher who submitted this paper'),
    sa.Column('student_name', sa.String(length=255), nullable=True, comment="Student's name"),
    sa.Column('student_id', sa.String(length=100), nullable=True, comment="Student's ID or roll number"),
    sa.Column('scanned_file_path', sa.String(length=500), nullable=False, comment='Storage path for scanned paper (MinIO/S3)'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='PaddleOCR extracted text from scanned paper'),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Question-wise evaluation results'),
    sa.Column('total_marks', sa.Integer(), nullable=False, comment='Maximum possible marks'),
    sa.Column('obtained_marks', sa.Float(), nullable=False, comment='Marks obtained by student'),
    sa.Column('percentage', sa.Float(), nullable=False, comment='Score percentage'),
    sa.Column('grade', sa.String(length=5), nullable=True, comment='Letter grade (A, B, C, etc.)'),
    sa.Column('overall_feedback', sa.Text(), nullable=True, comment='AI-generated overall feedback'),
    sa.Column('overall_feedback_gujarati', sa.Text(), nullable=True, comment='Overall feedback in Gujarati'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REVIEWED', 'APPROVED', name='checked_paper_status'), nullable=False, comment='Processing status'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='Teacher who reviewed this paper'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='When the paper was reviewed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_key_id'], ['answer_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add new columns to answer_keys
    op.add_column('answer_keys', sa.Column('user_id', sa.UUID(), nullable=False, comment='Teacher who created this answer key'))
    op.add_column('answer_keys', sa.Column('paper_id', sa.UUID(), nullable=True, comment='Optional linked question paper'))
    op.add_column('answer_keys', sa.Column('title', sa.String(length=255), nullable=False, comment='Answer key title'))
    op.add_column('answer_keys', sa.Column('subject', sa.String(length=100), nullable=True, comment='Subject (e.g., science, math)'))
    op.add_column('answer_keys', sa.Column('total_marks', sa.Integer(), nullable=False, comment='Total marks for all questions'))
    op.add_column('answer_keys', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of answer objects with keywords and variations'))
    op.add_column('answer_keys', sa.Column('marking_scheme', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Marking configuration (keyword weight, semantic threshold)'))
    
    # Drop old constraints and columns
    op.drop_constraint('answer_keys_question_paper_id_key', 'answer_keys', type_='unique')
    op.drop_constraint('answer_keys_question_paper_id_fkey', 'answer_keys', type_='foreignkey')
    op.create_foreign_key(None, 'answer_keys', 'question_papers', ['paper_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'answer_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer_keys', 'question_paper_id')
    op.drop_column('answer_keys', 'content')
    op.alter_column('graded_answers', 'question_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Snapshot of question text',
               existing_nullable=True)
    op.alter_column('graded_answers', 'student_answer_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Part of OCR text identified as this answer',
               existing_nullable=False)
    op.alter_column('graded_answers', 'feedback',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Specific feedback for this answer',
               existing_nullable=True)
    op.alter_column('graded_answers', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='AI confidence in grading (0-1)',
               existing_nullable=True)
    op.alter_column('submissions', 'input_file_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL of the uploaded answer sheet (PDF/Image)',
               existing_nullable=False)
    op.alter_column('submissions', 'student_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Extracted or provided student name',
               existing_nullable=True)
    op.alter_column('submissions', 'extracted_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw text content from OCR',
               existing_nullable=True)
    op.alter_column('submissions', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Overall performace summary',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'summary',
               existing_type=sa.TEXT(),
               comment='Overall performace summary',
               existing_nullable=True)
    op.alter_column('submissions', 'extracted_text',
               existing_type=sa.TEXT(),
               comment='Raw text content from OCR',
               existing_nullable=True)
    op.alter_column('submissions', 'student_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Extracted or provided student name',
               existing_nullable=True)
    op.alter_column('submissions', 'input_file_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL of the uploaded answer sheet (PDF/Image)',
               existing_nullable=False)
    op.alter_column('graded_answers', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='AI confidence in grading (0-1)',
               existing_nullable=True)
    op.alter_column('graded_answers', 'feedback',
               existing_type=sa.TEXT(),
               comment='Specific feedback for this answer',
               existing_nullable=True)
    op.alter_column('graded_answers', 'student_answer_text',
               existing_type=sa.TEXT(),
               comment='Part of OCR text identified as this answer',
               existing_nullable=False)
    op.alter_column('graded_answers', 'question_text',
               existing_type=sa.TEXT(),
               comment='Snapshot of question text',
               existing_nullable=True)
    op.add_column('answer_keys', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Map of question_id to grading criteria'))
    op.add_column('answer_keys', sa.Column('question_paper_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answer_keys', type_='foreignkey')
    op.drop_constraint(None, 'answer_keys', type_='foreignkey')
    op.create_foreign_key(op.f('answer_keys_question_paper_id_fkey'), 'answer_keys', 'question_papers', ['question_paper_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('answer_keys_question_paper_id_key'), 'answer_keys', ['question_paper_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('answer_keys', 'marking_scheme')
    op.drop_column('answer_keys', 'answers')
    op.drop_column('answer_keys', 'total_marks')
    op.drop_column('answer_keys', 'subject')
    op.drop_column('answer_keys', 'title')
    op.drop_column('answer_keys', 'paper_id')
    op.drop_column('answer_keys', 'user_id')
    op.drop_table('checked_papers')
    # ### end Alembic commands ###
