"""Add dictionary tables

Revision ID: e1aed1bb138b
Revises: d8b378484d56
Create Date: 2026-01-28 08:25:01.027981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1aed1bb138b'
down_revision: Union[str, Sequence[str], None] = 'd8b378484d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False, comment='Original word to translate'),
    sa.Column('language', sa.String(length=10), nullable=False, comment="Source language: 'en' or 'gu'"),
    sa.Column('translation', sa.String(length=255), nullable=False, comment='Translated word in target language'),
    sa.Column('transliteration', sa.String(length=255), nullable=True, comment='Romanized pronunciation'),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', name='part_of_speech'), nullable=False, comment='Grammatical category'),
    sa.Column('meaning', sa.Text(), nullable=False, comment='Definition in English'),
    sa.Column('meaning_gujarati', sa.Text(), nullable=True, comment='Definition in Gujarati'),
    sa.Column('example_sentence', sa.Text(), nullable=True, comment='Example usage in source language'),
    sa.Column('example_sentence_translation', sa.Text(), nullable=True, comment='Example translated to target language'),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of similar words'),
    sa.Column('antonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of opposite words'),
    sa.Column('audio_url', sa.String(length=500), nullable=True, comment='TTS pronunciation URL'),
    sa.Column('lookup_count', sa.Integer(), nullable=False, comment='Number of times looked up'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dictionary_lookup_count', 'dictionary_entries', ['lookup_count'], unique=False)
    op.create_index('idx_dictionary_word_language', 'dictionary_entries', ['word', 'language'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_word'), 'dictionary_entries', ['word'], unique=False)
    op.create_table('user_dictionary_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who performed the lookup'),
    sa.Column('dictionary_entry_id', sa.UUID(), nullable=False, comment='Word that was looked up'),
    sa.Column('lookup_count', sa.Integer(), nullable=False, comment='Number of times this user looked up this word'),
    sa.Column('last_looked_up', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Most recent lookup timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_entry_id'], ['dictionary_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_dict_history_last_lookup', 'user_dictionary_history', ['user_id', 'last_looked_up'], unique=False)
    op.create_index('idx_user_dict_history_user', 'user_dictionary_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_dict_history_user', table_name='user_dictionary_history')
    op.drop_index('idx_user_dict_history_last_lookup', table_name='user_dictionary_history')
    op.drop_table('user_dictionary_history')
    op.drop_index(op.f('ix_dictionary_entries_word'), table_name='dictionary_entries')
    op.drop_index('idx_dictionary_word_language', table_name='dictionary_entries')
    op.drop_index('idx_dictionary_lookup_count', table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    # ### end Alembic commands ###
