"""add_assignments

Revision ID: ef21326aef10
Revises: c3b9aec2ff24
Create Date: 2026-01-26 08:34:24.120093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef21326aef10'
down_revision: Union[str, Sequence[str], None] = 'c3b9aec2ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Student ID'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='Question content'),
    sa.Column('question_image_url', sa.String(length=500), nullable=True, comment='URL if image input'),
    sa.Column('input_type', sa.Enum('TEXT', 'IMAGE', 'PDF', name='input_type'), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='Subject classification'),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.Enum('SOLVE', 'HELP', name='assignment_mode'), nullable=False, comment='solve or help'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processing_status'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False, comment='gu, en, gu-en'),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Additional metadata'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignments_created', 'assignments', ['created_at'], unique=False)
    op.create_index('idx_assignments_user', 'assignments', ['user_id'], unique=False)
    op.create_table('assignment_solutions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ordered list of solution steps'),
    sa.Column('final_answer', sa.Text(), nullable=False, comment='Final answer text'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='Overall explanation'),
    sa.Column('difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty_level', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_table('help_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('current_hint_level', sa.Integer(), nullable=False, comment='Current hint level (0-5)'),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('interactions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='History of interactions (question, hint, response)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_sessions')
    op.drop_table('assignment_solutions')
    op.drop_index('idx_assignments_user', table_name='assignments')
    op.drop_index('idx_assignments_created', table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
